[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 160
target-version = ['py38', 'py39']
black_skip_string_normalization = true
include = '\.pyi?$'
extend-exclude = '''
/(
  | migrations
  | venv
  | .venv
  | tests
)/
'''
