# This is a basic workflow that is manually triggered

name: Testing

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
"on":
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  lint-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.9  # optional, default is 3.x

    - name: Install requirements
      run: |
        python -m pip install -r requirements-dev.txt

    - name: Run isort
      run: |
        python -m isort

    - name: Run flake8
      run: |
        python -m flake8

    - name: Run black
      run: |
        python -m black

    - name: Run pytest
      run: |
        python -m pytest

